#!/bin/bash

BAT_LEVEL=$(cat /sys/class/power_supply/BAT0/capacity)
BAT_STATUS=$(cat /sys/class/power_supply/BAT0/status)
CHARGING=""

if [[ $BAT_STATUS == *"Charging"* ]]; then
    CHARGING=" "
fi

# Display the battery icon that is closest the actual level
[ ${BAT_LEVEL} -ge 90 ] && echo "$CHARGING  $BAT_LEVEL " && exit 0
[ ${BAT_LEVEL} -ge 70 ] && echo "$CHARGING  $BAT_LEVEL" && exit 0
[ ${BAT_LEVEL} -ge 40 ] && echo "$CHARGING  $BAT_LEVEL" && exit 0
[ ${BAT_LEVEL} -ge 20 ] && echo "$CHARGING  $BAT_LEVEL" && exit 0
[ ${BAT_LEVEL} -ge 0 ]  && echo "$CHARGING  $BAT_LEVEL" && exit 0

if [ ! -z "$button" ]; then
    /usr/bin/i3-msg -q exec /usr/bin/gnome-control-center power
fi
