#!/bin/bash
# This time blocklet will use Xresources date format if defined
# or try to determine most appropriate format based on locale and GNOME settings.

DATE_FORMAT=`xrescat i3xrocks.date.format2`

TIME_FORMAT=$(gsettings get org.gnome.desktop.interface clock-format)

if [ "$TIME_FORMAT" == "'12h'" ]; then
    TIME_SPEC="%I:%M %p"
else
    TIME_SPEC="%H:%M"
fi

DATE_VALUE=$(date "+ $TIME_SPEC")

VALUE_COLOR=${color:-$(xrescat i3xrocks.value.color "#D8DEE9")}
VALUE_FONT=${font:-$(xrescat i3xrocks.value.font "Source Code Pro Medium 13")}
echo "<span font_desc=\"${VALUE_FONT}\" color=\"${VALUE_COLOR}\">$DATE_VALUE </span>"

if [ ! -z "$button" ]; then
    /usr/bin/i3-msg -q exec /usr/bin/gnome-control-center datetime
fi
